-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 08:41:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ss` DEFAULT CHARACTER SET utf8 ;
USE `ss` ;

-- -----------------------------------------------------
-- Table `ss`.`kws`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ss`.`kws` (
  `id` INT NOT NULL,
  `keyword` VARCHAR(255) NULL,
  `title` VARCHAR(45) NOT NULL,
  `site_url` VARCHAR(45) NULL,
  `shortnote` VARCHAR(45) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
